Mezgebe_web/mezgebe/expenses/routes.py
from mezgebe import db 
from flask import render_template, flash, redirect, url_for, abort, request, Blueprint, current_app
from mezgebe.expenses.forms import NewExpenseForm
from mezgebe.models import Expense, User
from flask_login import current_user, login_required

expenses = Blueprint('expenses', __name__)


@expenses.route('/expense/new_expense',  methods=['GET', 'POST'])
@login_required
def add_expense():
    """ A Route To Handle a Process To Create a New Expense By a User """
    new_expense_form = NewExpenseForm()
    if new_expense_form.validate_on_submit():
        new_expense = Expense(amount=new_expense_form.amount.data,
                              description=new_expense_form.description.data,
                              user_id=current_user.id)
        db.session.add(new_expense)
        db.session.commit()
        flash('New expense added successfully', 'success')
        return redirect(url_for('main.home'))
    return render_template('expenseform.html', form=new_expense_form)


@expenses.route('/expense/<int:expense_id>')
@login_required
def expense(expense_id):
    """ Retrive an expense associated with a given expense_id """
    expense = Expense.query.filter_by(id=expense_id).all()
    return render_template('expense.html', expense=expense[0])



@expenses.route('/expense/<int:expense_id>/update', methods=['GET', 'POST'])
@login_required
def update_expense(expense_id):
    """ Update An Expense Associated With a Given expense_id """
    expense = Expense.query.filter_by(id=expense_id).all()
    if expense[0].user_id != current_user.id:
        abort(403)
    new_expense_form = NewExpenseForm()
    if new_expense_form.validate_on_submit():
        expense[0].amount = new_expense_form.amount.data
        expense[0].description = new_expense_form.description.data
        db.session.commit()
        flash('Expense has been updated successfully!', 'success')
        return redirect(url_for('expenses.expense', expense_id=expense[0].id))
    elif request.method == 'GET':
        new_expense_form.amount.data = expense[0].amount
        new_expense_form.description.data = expense[0].description
    return render_template('expenseform.html', form=new_expense_form)



@expenses.route('/expense/<int:expense_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_expense(expense_id):
    """ Delete An Expense Associated With a Given expense_id """
    expense = Expense.query.filter_by(id=expense_id).all()
    if expense[0].user_id != current_user.id:
        abort(403)
    db.session.delete(expense[0])
    db.session.commit()
    flash('Expense has been deleted successfully!', 'success')
    return redirect(url_for('main.home'))

Mezgebe_web/mezgebe/main/routes.py
from flask import Blueprint, render_template 
from flask_login import current_user, login_required
from mezgebe.models import Expense
from mezgebe.models import User

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    """ A Route To Handle Home Page For a User """
    if current_user.is_authenticated:
        counter = 0
        expense = ''
        expenses = Expense.query.filter_by(user_id=current_user.id).all()
        if expenses:
            expense = 'exit'
        return render_template(
                'home.html', expense=expense, expenses=expenses, title='Home Page', counter=counter)
    else:
        return render_template('home_landing.html')

Mezgebe_web/mezgebe/users/routes.py
from flask import Blueprint, current_app
from mezgebe import db, bcrypt, mail
from mezgebe.models import User, Expense
from flask import render_template, flash, redirect, url_for, abort, request
from mezgebe.users.forms import UserRegisterationForm, UserLoginForm, PasswordResetForm, PasswordChangeForm
from flask_login import login_user, logout_user, current_user, login_required
from flask_mail import Message


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """ A Route To Handle a New User Registeration Process """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    registeration_form = UserRegisterationForm()
    if registeration_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(registeration_form.password.data).decode('utf-8')
        new_user = User(user_name=registeration_form.user_name.data,
                        first_name=registeration_form.first_name.data,
                        last_name=registeration_form.last_name.data,
                        email=registeration_form.email.data,
                        password=hashed_password
                        )
        db.session.add(new_user)
        db.session.commit()
        flash('Account has been created and you can now login!', 'success')
        return redirect(url_for('users.login'))
    return render_template('registeration.html', title='Register', form=registeration_form)


@users.route('/Login', methods=['GET', 'POST'])
def login():
    """ A Route To Handle a User Login Process """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    login_form = UserLoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(email=login_form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, login_form.password.data):
            login_user(user, remember=login_form.remember_me.data)
            return redirect(url_for('main.home'))
        else:
            flash('Invalid credential. Please check email or password!')
    return render_template('login.html', form=login_form)


@users.route('/Logout')
def logout():
    """ A Route TO Handle a User Logout Process """
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/account')
@login_required
def account():
    """ A Route To Handle a User Restriction """
    return render_template('account.html', title='Account')


def send_reset_email(user):
    """ A Function To Send a Password Reset
        Email For a User.

        - Flask_mail being used
    """
    token = (user.get_reset_token())
    reset_message = Message('Password Reset Request Instruction',
                            sender='danielshitaye10@gmail.com',
                            recipients=[user.email]
                            )
    reset_message.body = f'''Reset Your Password.
    {url_for('users.password_change', token=token, _external=True)}
    click on the link attached.'''

    mail.send(reset_message)



@users.route('/password_reset_request',  methods=['GET', 'POST'])
def password_reset():
    """ A Route To Handle a Password Reset Process """
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    reset_form = PasswordResetForm()
    if reset_form.validate_on_submit():
        user = User.query.filter_by(email=reset_form.email.data).first()
        send_reset_email(user)
        flash('Password Reset Email has been sent. Please Check Your Email.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_form.html', title='Password Reset', form=reset_form)



@users.route('/reset_password/<token>',  methods=['GET', 'POST'])
def password_change(token):
    """ A Route To Handle a Password Change Process """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_token(token)
    if user is None:
        flash('Password Reset Token is Invalid Or Expired.', 'warning')
        return redirect(url_for('password_reset'))
    reset_form = PasswordChangeForm()
    if reset_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
                reset_form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password has been changed successfull now you can login!', 'success')
        return redirect(url_for('users.login'))
    return render_template('password_change.html',
                               title='Password Change', form=reset_form)

Mezgebe_web/mezgebe/templates/account.html
{% extends 'layout.html' %}
{% block content %}
       <h1>{{ current_user.user_name</h1>
{% endblock content %}

Mezgebe_web/mezgebe/templates/expense.html
{% extends 'layout.html' %}
{% block content %}

<div class="mx-auto" style="width: 300px;">
  <p class="h3"> Expense Amount </p>
  <p> {{expense.amount}} </p>
  <p class="h3"> Reason of Expense </p>
  <p> {{expense.description}} </p>
  <P> {{expense.date.strftime('%Y-%m-%d')}} </p>
  <a href="{{ url_for('expenses.update_expense', expense_id=expense.id) }}">
	 <button class="btn btn-dark">UPDATE</button></a>
  <a href="{{ url_for('expenses.delete_expense', expense_id=expense.id) }}">
	  <button class="btn btn-dark">DELETE</button></a>
</div>
{% endblock content %}

Mezgebe_web/mezgebe/templates/expenseform.html
{% extends 'layout.html' %}
{% block content %}
    <div class="mx-auto" style="width:300px;">
	    <form method="POST" action="">
		    {{ form.hidden_tag() }}
		    <fieldset class="fields">
			    <legend class="legends" style=color:red> 
				    <p class="h3" style="color:black">
						 New Expense  
				    </p>
			</legend>
		<div class="fileds" style=margin-bottom:10px>
			 {{ form.amount.label(class="form-fileds") }}

                        {% if form.amount.errors %}
                            <div>
                                 {{ form.amount(class="form-fields is-invalid") }}
                                 {% for error in form.amount.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.amount(class="form-fields") }}
                         {% endif %}
                </div>

		<div class="fileds" style=margin-bottom:10px>
			  {{ form.description.label(class="form-fileds") }}

                        {% if form.description.errors %}
                            <div>
                                 {{ form.description(class="form-fields is-invalid") }}
                                 {% for error in form.description.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.description(class="form-fields") }}
                         {% endif %}
                </div>

		<div class="fileds">
                        {{ form.submit_button(class="btn btn-dark") }}
                </div>

		    </fieldset>
	    </form>
    </div>
{% endblock content %}

Mezgebe_web/mezgebe/templates/hom.html
{% extends 'layout.html' %}
{% block content %}
        {% for expense in expenses %}
	
	<div class="container" style=padding-bottom:10px;>
		<h5 class="bg-light"> Expense Amount </h5>
		<p class="text-dark"> {{expense.amount}}</p>
		<h5 class="bg-light"> Reason of Expense </h5>
		<p class="text-dark"> {{expense.description}} </p>
		<P> {{expense.date.strftime('%Y-%m-%d')}} </a></p>
	<a href="{{ url_for('expenses.expense', expense_id=expense.id) }}"
		class="btn btn-dark"> Manage Expense</a>
	</div>
	{% endfor %}
{% endblock content %}

Mezgebe_web/mezgebe/templates/home.html
{% extends 'layout.html' %}
{% block content %}

 <nav class="navbar navbar navbar-expand-md navbar-light fixed-top">

          <li class="nav-item active">
             <a  class="button btn btn-light"
                style="margin-left: 1100px; border:none; padding-left:20px; padding-right:20px;"
                href="{{url_for('expenses.add_expense')}}">
                     Create Expense <span class="sr-only">(current)</span> </a>
          </li>
	  <li class="nav-item">
             <a  class="button btn btn-light"
                style="margin-left: 0px; border:none; padding-left:20px; padding-right:20px;"
                href="{{url_for('users.logout')}}">
                     Logout <span class="sr-only">(current)</span> </a>
	  </li>
 </nav>
    <table class="table table-hover table-striped">
	    <thead class="thead-dark">
		    <tr>
			    <th scope="col">Expense Id</th>
			    <th scope="col">Amount</th>
			    <th scope="col">Reason</th>
			    <th scope="col">Date</th>
			    <th scope="col">Manage Expense</th>
		    </tr>
	    </thead>
<tbody>
	{% if expense=='exit' %}
	{% for expense in expenses %}
	<tr>
		<th scope="row">{{ expense.id }}</th>
		<td>{{ expense.amount }}</td>
		<td>{{ expense.description }}</td>
		<td>{{ expense.date.strftime('%Y-%m-%d')}} </td>
		<td> <a href="{{ url_for('expenses.expense', expense_id=expense.id) }}"
				> Manage </a>
		</td>
	</tr>
	{% endfor %}

	{% else %}
	<p> No Expense History Availaible
	<a href="{{url_for('expenses.add_expense')}}">Create New Expense</a>
	</P>
	{% endif %}
  </tbody>
</table>
</div>
{% endblock content %}

Mezgebe_web/mezgebe/templates/home_.html
{% extends 'layout.html' %}
{% block content %}
<table class="table table-hover table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Expense Id</th>
      <th scope="col">Amount</th>
      <th scope="col">Reason</th>
      <th scope="col">Date</th>
      <th scope="col">Manage Expense</th>
    </tr>
  </thead>
  <tbody>
	{% for expense in expenses %}
	<tr>
		<th scope="row">{{ expense.id }}</th>
		<td>{{ expense.amount }}</td>
		<td>{{ expense.description }}</td>
		<td>{{ expense.date.strftime('%Y-%m-%d')}} </td>
		<td> <a href="{{ url_for('expenses.expense', expense_id=expense.id) }}"
				> Manage </a>
		</td>
	</tr>
	{% endfor %}
  </tbody>
</table>
{% endblock content %}

Mezgebe_web/mezgebe/templates/home_landing.html
{% extends 'layout.html' %}
{% block content %}
<nav class="navbar navbar navbar-expand-md navbar-light fixed-top">
  <a class="navbar-brand" href="#">Mezgebe</a>
</nav>

<div style="padding-top: 30px;">
	<p class="h1" style="margin-left:300px;"> Mezgebe Expense Tracker <p>
	<div style="padding-top: 55px; margin-left:400px;">
		<a  class="button btn btn-dark"
                style="padding-left:20px; padding-right:20px; "
                href="{{url_for('users.login')}}">
                     Login <span class="sr-only">(current)</span> 
	</a>
	<a class="button btn btn-dark" style="margin-left:35px; padding-left:20px; padding-right:20px; " href="{{ url_for('users.register') }}">
                Register </a>
	</div>
</div>
{% endblock content %}

Mezgebe_web/mezgebe/templates/landing_page.html
<!DOCTYPE html>
<html>
  <head>
    <title>Mezgebe Expense Tracker</title>
  </head>
  <body>
    <div style="font-size:40px; color:green; font-family:Georgia, 'Times New Roman', Times, serif:green; border-width:1px; border-style: solid; width:550px; height:500px; padding-left:200px;">
      <div style="color:red; width:550px; height:100px; border-width:0.5px; border-style:solid;"><P>Mezgebe Expense Tracker</P></div>
    </div>
  </body>
</html>

Mezgebe_web/mezgebe/templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	
		{% if title %}
		     <title>Mezgebe {{ title }}</title>
		{% else %}
		     <title>Mezgebe Expense Tracker</title>
		{% endif %}

	</head>
	
	<body style="background-color: light-grey;">
		<div class="container"  style="margin-bottom: 130px;">
			<nav class="navbar navbar navbar-expand-md navbar-light fixed-top">
				<a class="navbar-brand" href="{{ url_for('main.home') }}">Mezgebe</a>
			</nav>
		</div>

		{% with messages = get_flashed_messages(with_categories=True) %}
		   {% if messages %}
		       {% for category, message in messages %}
		         <div class="alert alert-dark" role="alert" style="margin-left:450px; 
				 width:500px;">
				 {{ message }}
			 </div>
		       {% endfor %}
		   {% endif %}
		{% endwith %}
	<div class="container">
		{% block content %} {% endblock %}
	</div>

	<nav class="navbar fixed-bottom navbar-light bg-dark">
		<a class="navbar-brand" href="#"></a>
	</nav>

	 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	
	</body>
</html>

Mezgebe_web/mezgebe/templates/login.html
{% extends 'layout.html' %}
{% block content %}

<div class="container"  style="margin-bottom: 130px;">
<nav class="navbar navbar navbar-expand-md navbar-light fixed-top">
	<a class="navbar-brand" href="{{url_for('main.home') }}">Mezgebe</a>
</nav>
</div>

    <div class="mx-auto" style="width: 500px;">
	    <form method="POST" action="">
		    {{ form.hidden_tag() }}
		    <fieldset class="fields">
			    <legend class="legends h3" style=color:black> 
				    Login  
			</legend>
		<div class="form-group">
			 {{ form.email.label(class="form") }}

                        {% if form.email.errors %}
                            <div>
                                 {{ form.email(class="form-control-sm is-invalid") }}
                                 {% for error in form.email.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.email(class="form-control-sm") }}
                         {% endif %}
                </div>

		<div class="form-group">
			  {{ form.password.label(class="form") }}

                        {% if form.password.errors %}
                            <div>
                                 {{ form.password(class="form-control-sm is-invalid") }}
                                 {% for error in form.password.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.password(class="form-control-sm") }}
                         {% endif %}
                </div>

		<div class="form-group">
                        {{ form.submit_button(class="btn btn-dark") }}
                </div>

		    </fieldset>
	    </form> 
	    <div class="existing_acount"> Forget Your Password? 
		    <a href="{{ url_for('users.password_reset') }}"> Reset password </a>
	    </div>

	     <div> Do not you have an Account?
                    <a href="{{ url_for('users.register') }}"> Create new account </a>
            </div>

    </div>
{% endblock content %}

Mezgebe_web/mezgebe/templates/password_change.html
{% extends 'layout.html' %}
{% block content %}
    <div class="mx-auto" style="width:300px;">
	    <form method="POST" action="">
		    {{ form.hidden_tag() }}
		    <fieldset class="fields">
			    <legend class="legends h3" style="color:black"> 
				    Password Change Form 
			</legend>

		<div class="form-group">
			  {{ form.password.label(class="form-fileds-lg") }}

                        {% if form.password.errors %}
                            <div>
                                 {{ form.password(class="form-control is-invalid") }}
                                 {% for error in form.password.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.password(class="form-fields") }}
                         {% endif %}
                </div>

		<div class="form-group">

			 {{ form.confirm_password.label(class="form") }}

                        {% if form.confirm_password.errors %}
                            <div>
                                 {{ form.confirm_password(class="form-filed is-invalid") }}
                                 {% for error in form.confirm_password.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.confirm_password(class="form-fields") }}
                         {% endif %}

                </div>

		<div class="fileds">
                        {{ form.submit_button(class="btn btn-dark") }}
                </div>

		    </fieldset>
	    </form>
    </div>
{% endblock content %}

Mezgebe_web/mezgebe/templates/registeration.html
{% extends 'layout.html' %}
{% block content %}
    <div class="mx-auto" style="width: 400px;">
	    <form method="POST" action="">
		    {{ form.hidden_tag() }}
		    <fieldset class="fields">
			    <legend class="legends h3" style="color:black"> 
				    Register Now & Track Your Expenses 
			</legend>
		<div class="fileds">
			{{ form.first_name.label(class="form-fileds") }}
			
			{% if form.first_name.errors %}
			    <div>
			         {{ form.first_name(class="form-fields is-invalid") }}
			         {% for error in form.first_name.errors %}
				 <span> {{ error }} </span>
			         {% endfor %}
			 </div>
			{% else %}
			   {{ form.first_name(class="form-fields") }}
			 {% endif %}
		</div>

		<div class="fileds">

			{{ form.last_name.label(class="form-fileds") }}

                        {% if form.last_name.errors %}
                            <div>
                                 {{ form.last_name(class="form-fields is-invalid") }}
                                 {% for error in form.last_name.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.last_name(class="form-fields") }}
                         {% endif %}

                </div>
		<div class="fileds">
			{{ form.user_name.label(class="form-fileds") }}
			
			{% if form.user_name.errors %}
                            <div>
                                 {{ form.user_name(class="form-fields is-invalid") }}
                                 {% for error in form.user_name.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
			   {{ form.user_name(class="form-fields") }}
			 {% endif %}
                </div>
		<div class="fileds">
			 {{ form.email.label(class="form-fileds") }}

                        {% if form.email.errors %}
                            <div>
                                 {{ form.email(class="form-fields is-invalid") }}
                                 {% for error in form.email.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.email(class="form-fields") }}
                         {% endif %}
                </div>

		<div class="fileds">
			  {{ form.password.label(class="form-fileds") }}

                        {% if form.password.errors %}
                            <div>
                                 {{ form.password(class="form-fields is-invalid") }}
                                 {% for error in form.password.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.password(class="form-fields") }}
                         {% endif %}
                </div>

		<div class="fileds">

			 {{ form.confirm_password.label(class="form-fileds") }}

                        {% if form.confirm_password.errors %}
                            <div>
                                 {{ form.confirm_password(class="form-fields is-invalid") }}
                                 {% for error in form.confirm_password.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.confirm_password(class="form-fields") }}
                         {% endif %}

                </div>

		<div class="fileds">
                        {{ form.submit_button(class="btn btn-dark") }}
                </div>

		    </fieldset>
	    </form>
	    
	    <div class="existing_acount"> Already Have an Account? 
		    <a href="{{ url_for('users.login') }}"> Sign In </a>
	    </div>
    </div>
{% endblock content %}

Mezgebe_web/mezgebe/templates/reset_form.html
{% extends 'layout.html' %}
{% block content %}
    <div class="mx-auto" style="width: 300px;">
	    <form method="POST" action="">
		    {{ form.hidden_tag() }}
		    <fieldset class="form-group">
			    <legend class="mb-3" style=color:red> 
				    <p class="h3" style="color: black;"> 
						 Password Reset Form 
				   </p>
		
			    </legend>

		<div class="form-group">
			 {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            <div>
                                 {{ form.email(class="form-control-sm is-invalid") }}
                                 {% for error in form.email.errors %}
                                 <span> {{ error }} </span>
                                 {% endfor %}
                         </div>
                        {% else %}
                           {{ form.email(class="form-control-sm is-invalid") }}
                         {% endif %}
                </div>

		
		<div class="fileds">
                        {{ form.submit_button(class="btn btn-dark") }}
                </div>

		    </fieldset>
	    </form>
    </div>
{% endblock content %}